### ISSUE TITLE
Scoreboard Azure Hands-On - Porto 2015-11-21 - ISEP

### ISSUE THREAD

**Issue by askpt** [askpt/AzureLabDemo#1]
Quem já tem site public, publique aqui nas respostas o endereço p.f.

**Comment by BrunoMRP** [comment]
https://websitezinho.azurewebsites.net/

**Comment by tmrocha89** [comment]
http://uemetis.azurewebsites.net/

**Comment by dnamorim** [comment]
http://dnamorimazuredemo.azurewebsites.net/

**Comment by danieljalopes** [comment]
http://isepdemodaniellopes.azurewebsites.net/

**Comment by askpt** [comment]
http://isepdemo.azurewebsites.net/

**Comment by sergioliveira** [comment]
http://isepdemoapp.azurewebsites.net/

**Comment by ricardodnb** [comment]
https://ricardogomes.azurewebsites.net/

**Comment by ajmlima** [comment]
http://ajmlt.azurewebsites.net/

**Comment by FabioSa222** [comment]
http://isepdemo1120038.azurewebsites.net/

**Comment by InsaniTea** [comment]
http://isepdemo-pedro-coelho.azurewebsites.net/

**Comment by soaressergiocom** [comment]
http://soaressfdevscophandson.azurewebsites.net/
